name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 2.2.0
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  yaml: ^3.1.0
  resource_portable: ^3.0.0
  path: ^1.6.2
  file: '>=6.0.0'
  archive: ^4.0.2
  platform: ^3.0.0
  process: ^5.0.3
  meta: ^1.1.6
  intl: '>=0.20.1'
  tool_mobile:
    git: https://github.com/Ralf-Kraemer/tool_mobile.git

dev_dependencies:
  test: ^1.16.8
  test_api: ^0.7.4
  mockito: ^5.4.5
  pedantic: ^1.11.0
  quiver: ^3.2.2
  collection: any

executables:
  screenshots: main
